export const CREATE_WEBHOOK_MODAL = 'CREATE_WEBHOOK'
export const EDIT_WEBHOOK_MODAL = 'EDIT_WEBHOOK'
export const TEST_WEBHOOK_MODAL = 'TEST_WEBHOOK'
export const DELETE_WEBHOOK_MODAL = 'DELETE_WEBHOOK'
