export const CREATE_AUTOMATION_RULE_MODAL = 'CREATE_AUTOMATION_RULE_MODAL'
export const EDIT_AUTOMATION_RULE_MODAL = 'EDIT_AUTOMATION_RULE_MODAL'
export const DELETE_AUTOMATION_RULE_MODAL = 'DELETE_AUTOMATION_RULE_MODAL'
